const CWS = 'https://chrome.google.com/webstore/devconsole/4fa4fdba-7111-41cc-bf36-56cf5e090a3e/nicchanfaefmmnkmemgkppipghgknkek/edit';
await mcp('navigate', { url: 'https://example.com' });
await sleep(2500);
let s = await mcp('snapshot', {}); let t = await mcp('getText', {});
console.log('example nodes:', (s?.result?.nodes??[]).length, 'text:', (t?.result?.text??'').replace(/\s+/g,' ').slice(0,80));
await mcp('navigate', { url: CWS });
await sleep(4000);
s = await mcp('snapshot', {}); t = await mcp('getText', {});
console.log('cws nodes:', (s?.result?.nodes??[]).length, 'text:', (t?.result?.text??'').replace(/\s+/g,' ').slice(0,120));
process.exit(0);
