const tabs = await mcp('listTabs', {});
console.log('TABS:', JSON.stringify(tabs?.result));
const ctx = await mcp('pageContext', {});
console.log('CTX:', JSON.stringify(ctx?.result));
const snap = await mcp('snapshot', {});
const ns = snap?.result?.nodes ?? [];
const txt = await mcp('getText', {});
console.log('nodes:', ns.length, '| textlen:', (txt?.result?.text ?? '').length);
console.log('sample:', ns.slice(0, 25).map((n) => `${n.ref}:${n.role}:${(n.label||'').slice(0,34)}`).join(' | '));
console.log('text:', (txt?.result?.text ?? '').replace(/\s+/g,' ').slice(0, 260));
process.exit(0);
